OPTS	= -O3 -DUSE_SECTION_MULTICAST
MOL3D	= ..
BINARY	= mol3d
CHARMC	= ../../../../bin/charmc

MAKE_MOL3D_CHARM	= $(MOL3D)/src_charm
MAKE_MOL3D_PHYSICS	= $(MOL3D)/src_physics
MAKE_MOL3D_NAMDSRC	= $(MOL3D)/src_namd
